//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.296
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edleditor {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("edleditor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Animations {
            get {
                object obj = ResourceManager.GetObject("Animations", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Application {
            get {
                object obj = ResourceManager.GetObject("Application", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Base {
            get {
                object obj = ResourceManager.GetObject("Base", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Colors {
            get {
                object obj = ResourceManager.GetObject("Colors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Controls {
            get {
                object obj = ResourceManager.GetObject("Controls", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CutBox {
            get {
                object obj = ResourceManager.GetObject("CutBox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CutBoxItem {
            get {
                object obj = ResourceManager.GetObject("CutBoxItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FontNames {
            get {
                object obj = ResourceManager.GetObject("FontNames", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HeaderText {
            get {
                object obj = ResourceManager.GetObject("HeaderText", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Images {
            get {
                object obj = ResourceManager.GetObject("Images", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ListBoxItem {
            get {
                object obj = ResourceManager.GetObject("ListBoxItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ListboxNoFocus {
            get {
                object obj = ResourceManager.GetObject("ListboxNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Menu {
            get {
                object obj = ResourceManager.GetObject("Menu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PlayRateButton {
            get {
                object obj = ResourceManager.GetObject("PlayRateButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SimpleButton {
            get {
                object obj = ResourceManager.GetObject("SimpleButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SimpleListBox {
            get {
                object obj = ResourceManager.GetObject("SimpleListBox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Sounds {
            get {
                object obj = ResourceManager.GetObject("Sounds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VideoEditor {
            get {
                object obj = ResourceManager.GetObject("VideoEditor", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
